name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install graphviz 
        run: sudo apt install xdot -y

      - name: Compile 
        run: make everything 
